langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: juYgp+TGP1IY3Z29netxTJHyBAbq14U4Xb/jUTk7UgJVumT5esXKg3uWYe9h7kozchlS3rNfnN51lmAePtB57wejfCoPeopW/8rP+gkPqPGNBenrpOg4W7DDavGIH3rrRUzORisi/8u1nvOGaFJg2PoExvNobcfLnVsUbIUH1vjjZnoGtABk7ht5Cwk/Vmp/YWXGgoYyA0Vp1aWYr3Rwh/UcOmnxFS48v1BujSSOniQD7sODqIohOgaBXLTsBmaqzIytDAQJe+LmpxRt772b9zEMsPIH2VmI1LxlqJgtdRcrEULVr2wJAY2bg7BQ2upijZB/2oMLfWNRdqGyXeIR5WgspT2qzt2+QaAfCUsVAs5Q+DnhLmx8FAQm33avqRSQJDA7rSARHhe5N97cjDTfsO/5FI515AsBPakodNYOj/D3hHpS9v86blgA3DNbMvTXoo71dXbuBVMlHNB8QXJRKwHXQb5Umj/bdT7VZQ8KxYF21vgLVI/LknLfGG7qTBW73UAo7TSQlQxkxqj7hLPjInstb7LCgT69h/pW9Pz87G3Bh0cpfwbC6gmN7oY87a23rA8SSJOWix3cSL/rdWpmMne0Tcv0QLKg0RNDxb16M8UULZJ+Vl2gzX2rqmXOrlep94jrDQkpdaNpeItFZku3DLBetbiPmt4FgGG9S+vf9/c=
  app: yearone-api
  on:
    repo: NickEdwin/yearone_api
    branch: main
  skip_cleanup: 'true'
